ecommerce.webui/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Iyzipay;
using Iyzipay.Model;
using Iyzipay.Request;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ecommerce.business.Abstract;
using ecommerce.entity;
using ecommerce.webui.Identity;
using ecommerce.webui.Models;

namespace ecommerce.webui.Controllers
{
    [Authorize]
    public class CartController:Controller
    {
        private ICartService _cartService;
        private IOrderService _orderService;
        private UserManager<User> _userManager;
        public CartController(IOrderService orderService,ICartService cartService,UserManager<User> userManager)
        {
            _cartService = cartService;
            _orderService = orderService;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));
            return View(new CartModel(){
                CartId = cart.Id,
                CartItems = cart.CartItems.Select(i=>new CartItemModel()
                {
                    CartItemId = i.Id,
                    ProductId = i.ProductId,
                    Name = i.Product.Name,
                    Price = (double)i.Product.Price,
                    ImageUrl = i.Product.ImageUrl,
                    Quantity =i.Quantity

                }).ToList()
            });
        } 

        [HttpPost]
        public IActionResult AddToCart(int productId,int quantity)
        {
            var userId = _userManager.GetUserId(User);
            _cartService.AddToCart(userId,productId,quantity);
            return RedirectToAction("Index");
        } 

        [HttpPost]
        public IActionResult DeleteFromCart(int productId)
        {
             var userId = _userManager.GetUserId(User);
            _cartService.DeleteFromCart(userId,productId);
            return RedirectToAction("Index");
        }

        public IActionResult Checkout()
        {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));
            
            var orderModel = new OrderModel();

            orderModel.CartModel = new CartModel()
            {
                CartId = cart.Id,
                CartItems = cart.CartItems.Select(i=>new CartItemModel()
                {
                    CartItemId = i.Id,
                    ProductId = i.ProductId,
                    Name = i.Product.Name,
                    Price = (double)i.Product.Price,
                    ImageUrl = i.Product.ImageUrl,
                    Quantity =i.Quantity

                }).ToList()
            };
            
            return View(orderModel);
        }

        [HttpPost]
        public IActionResult Checkout(OrderModel model)
        {
            if(ModelState.IsValid)
            {            
                var userId = _userManager.GetUserId(User);                
                var cart = _cartService.GetCartByUserId(userId);
                //aralık
                var orders =_orderService.GetOrders(userId);

                var orderListModel = new List<OrderListModel>();
                OrderListModel orderModel;
                foreach (var order in orders)
                {
                    orderModel = new OrderListModel();

                    orderModel.OrderId = order.Id;
                    orderModel.OrderNumber = order.OrderNumber;
                    orderModel.OrderDate = order.OrderDate;
                    orderModel.Phone = order.Phone;
                    orderModel.FirstName = order.FirstName;
                    orderModel.LastName = order.LastName;
                    orderModel.Email = order.Email;
                    orderModel.Address = order.Address;
                    orderModel.City = order.City;
                    orderModel.OrderState = order.OrderState;
                    orderModel.PaymentType = order.PaymentType;

                    orderModel.OrderItems = order.OrderItems.Select(i=>new OrderItemModel(){
                            OrderItemId = i.Id,
                            Name = i.Product.Name,
                            Price = (double)i.Price,
                            Quantity = i.Quantity,
                            ImageUrl = i.Product.ImageUrl
                    }).ToList();

                    orderListModel.Add(orderModel);
                }
                // aralık
                model.CartModel = new CartModel()
                {
                    CartId = cart.Id,
                    CartItems = cart.CartItems.Select(i=>new CartItemModel()
                    {
                        CartItemId = i.Id,
                        ProductId = i.ProductId,
                        Name = i.Product.Name,
                        Price = (double)i.Product.Price,
                        ImageUrl = i.Product.ImageUrl,
                        Quantity =i.Quantity
                    }).ToList()
                };

                var payment = PaymentProcess(model);

                if(payment.Status=="success")
                {
                    SaveOrder(model,payment,userId);
                    ClearCart(model.CartModel.CartId);
                    return View("Success", orderListModel);
                }else
                {
                    var msg = new AlertMessage()
                    {            
                        Message = $"{payment.ErrorMessage}",
                        AlertType = "danger"
                    };

                    TempData["message"] =  JsonConvert.SerializeObject(msg);
                    }
                }
            return View(model);
        }

        public IActionResult GetOrders()
        {
            var userId = _userManager.GetUserId(User);    
            var orders =_orderService.GetOrders(userId);

            var orderListModel = new List<OrderListModel>();
            OrderListModel orderModel;
            foreach (var order in orders)
            {
                orderModel = new OrderListModel();

                orderModel.OrderId = order.Id;
                orderModel.OrderNumber = order.OrderNumber;
                orderModel.OrderDate = order.OrderDate;
                orderModel.Phone = order.Phone;
                orderModel.FirstName = order.FirstName;
                orderModel.LastName = order.LastName;
                orderModel.Email = order.Email;
                orderModel.Address = order.Address;
                orderModel.City = order.City;
                orderModel.OrderState = order.OrderState;
                orderModel.PaymentType = order.PaymentType;

                orderModel.OrderItems = order.OrderItems.Select(i=>new OrderItemModel(){
                        OrderItemId = i.Id,
                        Name = i.Product.Name,
                        Price = (double)i.Price,
                        Quantity = i.Quantity,
                        ImageUrl = i.Product.ImageUrl
                }).ToList();

                orderListModel.Add(orderModel);
            }


            return View("Orders", orderListModel);
        }

        private void ClearCart(int cartId)
        {
            _cartService.ClearCart(cartId);
        }

        private void SaveOrder(OrderModel model, Payment payment, string userId)
        {
           var order = new Order();

           order.OrderNumber = new Random().Next(111111,999999).ToString();
           order.OrderState = EnumOrderState.completed;
           order.PaymentType = EnumPaymentType.CreditCard;
           order.PaymentId = payment.PaymentId;
           order.ConversationId = payment.ConversationId;
           order.OrderDate = new DateTime();
           order.FirstName = model.FirstName;
           order.LastName = model.LastName;
           order.UserId = userId;
           order.Address = model.Address;
           order.Phone = model.Phone;
           order.Email = model.Email;
           order.City = model.City;
           order.Note = model.Note;

           order.OrderItems = new List<entity.OrderItem>();

            foreach (var item in model.CartModel.CartItems)
            {
                var orderItem = new ecommerce.entity.OrderItem()
                {
                    Price = item.Price,
                    Quantity = item.Quantity,
                    ProductId = item.ProductId
                };
                order.OrderItems.Add(orderItem);
            }
            _orderService.Create(order);
        }

        private Payment PaymentProcess(OrderModel model)
        {
            Options options = new Options();
            options.ApiKey = "sandbox-RStpAR6sBz86RpFTuWPyF7hjh8c8g9E4";
            options.SecretKey = "sandbox-0zu0oxpXipwFsSGu1FrSofDVhTrWig2p";
            options.BaseUrl = "https://sandbox-api.iyzipay.com";
                    
            CreatePaymentRequest request = new CreatePaymentRequest();
            request.Locale = Locale.TR.ToString();
            request.ConversationId = new Random().Next(111111111,999999999).ToString();
            request.Price = model.CartModel.TotalPrice().ToString();
            request.PaidPrice = model.CartModel.TotalPrice().ToString();
            request.Currency = Currency.TRY.ToString();
            request.Installment = 1;
            request.BasketId = "B67832";
            request.PaymentChannel = PaymentChannel.WEB.ToString();
            request.PaymentGroup = PaymentGroup.PRODUCT.ToString();

            PaymentCard paymentCard = new PaymentCard();
            paymentCard.CardHolderName = model.CardName;
            paymentCard.CardNumber = model.CardNumber;
            paymentCard.ExpireMonth = model.ExpirationMonth;
            paymentCard.ExpireYear = model.ExpirationYear;
            paymentCard.Cvc = model.Cvc;
            paymentCard.RegisterCard = 0;
            request.PaymentCard = paymentCard;

ecommerce.webui/Controllers/ShopController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using ecommerce.business.Abstract;
using ecommerce.entity;
using ecommerce.webui.Models;
using System.Collections.Generic;
using ecommerce.data.Concrete.EfCore;

namespace ecommerce.webui.Controllers
{
    public class ShopController:Controller
    {
        private IProductService _productService;
        private IProductCommentService _productCommentService;
        public ShopController(IProductService productService, IProductCommentService productCommentService)
        {
            this._productService=productService;
            this._productCommentService=productCommentService;
        }

        // localhost/products/telefon?page=1
        public IActionResult List(string sortOrder, string category,int page=1)
        {
            const int pageSize=6;
            ViewData["PriceOrderDesc"] = "price_desc";
            ViewData["PriceOrderInc"] = "price_inc";
            var productViewModel = new ProductListViewModel()
            {
                PageInfo = new PageInfo()
                {
                    TotalItems = _productService.GetCountByCategory(category),
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    CurrentCategory = category
                },
                Products = _productService.GetProductsByCategory(category,page,pageSize,sortOrder)
            };

            return View(productViewModel);
        }

        public IActionResult Details(string url)
        {
            if (url==null)
            {
                return NotFound();
            }
            Product product = _productService.GetProductDetails(url);
            if(product==null)
            {
                return NotFound();
            }
            ProductCommentViewModel vm = new ProductCommentViewModel();

            var products = _productService.GetAll().Take(5);

            vm.Products = products.ToList();

            vm.Title = product.Name;

            var productId = product.ProductId;
            
            var comments = _productCommentService.GetProductComment(product);
            vm.ListOfComments = comments;

            var ratings = _productCommentService.GetProductComment(product);
            if(ratings.Count() > 0)
            {
                var ratingSum = ratings.Sum( d=> d.Rating);
                ViewBag.RatingSum = ratingSum;
                var ratingCount = ratings.Count();
                ViewBag.RatingCount = ratingCount;
            }
            else
            {
                ViewBag.RatingSum = 0;
                ViewBag.RatingCount = 0;
            }
            vm.Product = product;
            vm.Categories = product.ProductCategories.Select(i=>i.Category).ToList();
            return View(vm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Details(ProductCommentViewModel vm)
        {
            var comment = vm.Comment;
            var productId = vm.Product.ProductId;
            var rating = vm.Rating;
            var userName = vm.UserName;

            ProductComment ProductComment = new ProductComment()
            {
                ProductId = productId,
                Comments = comment,
                Rating = rating,
                PublishedDate = DateTime.Now,
                UserName = userName
            };

            _productCommentService.AddProductComment(ProductComment);
            return RedirectToAction("Details","Shop", new{ url = vm.Product.Url});
        }

        public IActionResult Search(string q)
        {
            var productViewModel = new ProductListViewModel()
            {
                Products = _productService.GetSearchResult(q)
            };

            return View(productViewModel);
        }
    }
}

ecommerce.webui/ViewComponents/CategoriesViewComponent.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using ecommerce.business.Abstract;

namespace ecommerce.webui.ViewComponents
{
    public class CategoriesViewComponent:ViewComponent
    {
        private ICategoryService _categoryService;
        public CategoriesViewComponent(ICategoryService categoryService)
        {
            this._categoryService=categoryService;
        }
        public IViewComponentResult Invoke()
        {
            if (RouteData.Values["category"]!=null)
                ViewBag.SelectedCategory = RouteData?.Values["category"];
                
            return View(_categoryService.GetAll());
        }
    }
}

ecommerce.webui/Views/Shop/Details.cshtml
@model ProductCommentViewModel

@{
	var ratingSum = ViewBag.RatingSum;
	var ratingCount = ViewBag.RatingCount;

	decimal rating = 0;
	if(ratingCount > 0)
	{
		rating = (ratingSum/ratingCount);
	}

	var totalRating = decimal.Parse(rating.ToString());
}
<!DOCTYPE html>
<html>
<head>
<title>Ürün Detayları</title>
<link rel="stylesheet" href="/modules/bootstrap/dist/css/bootstrap.min.css" crossorigin="anonymous">
<link href="~/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
<!--theme-style-->
<link href="~/css/mystyles.css" rel="stylesheet" type="text/css" media="all" />	
<link rel="stylesheet" href="~/css/etalage.css" type="text/css" media="all" />
<!--//theme-style-->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--fonts-->
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
<!--//fonts-->
<script src="~/js/jquery.min.js"></script>

<script src="~/js/jquery.etalage.min.js"></script>
<script>
			jQuery(document).ready(function($){

				$('#etalage').etalage({
					thumb_image_width: 300,
					thumb_image_height: 400,
					source_image_width: 900,
					source_image_height: 1200,
					show_hint: true,
					click_callback: function(image_anchor, instance_id){
						alert('Callback example:\nYou clicked on an image with the anchor: "'+image_anchor+'"\n(in Etalage instance: "'+instance_id+'")');
					}
				});

			});
		</script>
<style>
.now-get{
	font-size: 1.1em;
	color:#fff;
	padding:0.6em 0.8em;
	background:#323A45;
	text-decoration: none;
}
.now-get:hover{
	background: #0D3F84;
}
.get-cart{
	float:right;
	padding: 0.4em 0.6em;
	font-size: 1em;
}
.get-cart-in{
	float:right;
}
.dl-horizontal dt {
	white-space: normal;
}
input,
select,
textarea{
	max-width: 280px;
}
.commentBox {
	background-color: #efefef;
	padding: 10px;
	border-radius: 10px;
}
.starGlowN {
	background-image: url('../img/starglow.gif');
	min-width: 30px;
	min-height: 30px;
	display: inline-block;
}
.starGlow {
	background-image: url('../img/starglow.gif');
	min-width: 30px;
	min-height: 30px;
	display: inline-block;
	cursor: pointer;
}
.starFade {
	background-image: url('../img/StarFade.gif');
	min-width: 30px;
	min-height: 30px;
	display: inline-block;
	cursor: pointer;
}
.starFadeN {
	background-image: url('../img/StarFade.gif');
	min-width: 30px;
	min-height: 30px;
	display: inline-block;
}
</style>

</head>
<body>
@await Html.PartialAsync("_header") 
<div class="container"> 
	 	
	<div class=" single_top">
		<div class="single_grid">
			<div class="grid images_3_of_2">
					<ul id="etalage">
						<li>
							<a href="optionallink.html">
								<img class="etalage_thumb_image" src="~/img/3070TIBig.jpg" class="img-responsive" />
								<img class="etalage_source_image" src="~/img/3070TIBig.jpg" class="img-responsive" title="" />
							</a>
						</li>
					</ul>
						<div class="clearfix"> </div>		
				</div> 
				<div class="desc1 span_3_of_2">
				
				
				<h4>@Model.Product.Name</h4>
				<div style="">
					<span class="starFadeN" id="sRate1"></span>
					<span class="starFaden" id="sRate2"></span>
					<span class="starFaden" id="sRate3"></span>
					<span class="starFaden" id="sRate4"></span>
					<span class="starFaden" id="sRate5"></span>
				</div>
			<div class="cart-b">
				<div class="left-n ">@Model.Product.Price</div>
				<form asp-controller="Cart" asp-action="AddToCart" method="POST">
					<input type="hidden" name="productId" value="@Model.Product.ProductId">
					<input type="hidden" name="quantity" value="1">
					<button class="now-get get-cart-in" href="#">SEPETE EKLE</button> 
				</form>
				<div class="clearfix"></div>
				</div>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
			</div>
			<div class="clearfix"> </div>
			</div>
			<ul id="flexiselDemo1">
				@foreach (var item in Model.Products)
				{
					<li><img src="~/img/@item.ImageUrl" /><div class="grid-flex"><a href="/@item.Url">@item.Name</a><p>@item.Price TL</p></div></li>
				}
				@* <li><img src="~/img/1660S.jpg" /><div class="grid-flex"><a href="/1660S">1660S</a><p>10000 TL</p></div></li>
				<li><img src="~/img/6500XT.jpg" /><div class="grid-flex"><a href="/6500XT">6500XT</a><p>8800 TL</p></div></li>
				<li><img src="~/img/6700XT.jpg" /><div class="grid-flex"><a href="/6700XT">6700XT</a><p>15000 TL</p></div></li>
				<li><img src="~/img/1660TI.jpg" /><div class="grid-flex"><a href="/1660TI">1660TI</a><p>11500 TL</p></div></li>
				<li><img src="~/img/2060.jpg" /><div class="grid-flex"><a href="/2060">2060</a><p>13000 TL</p></div></li> *@
			</ul>
	<script type="text/javascript">
		$(window).load(function() {
		$("#flexiselDemo1").flexisel({
			visibleItems: 5,
			animationSpeed: 1000,
			autoPlay: true,
			autoPlaySpeed: 3000,    		
			pauseOnHover: true,
			enableResponsiveBreakpoints: true,
			responsiveBreakpoints: { 
				portrait: { 
					changePoint:480,
					visibleItems: 1
				}, 
				landscape: { 
					changePoint:640,
					visibleItems: 2
				},
				tablet: { 
					changePoint:768,
					visibleItems: 3
				}
			}
		});
		
	});
	</script>
	<script type="text/javascript" src="js/jquery.flexisel.js"></script>

	<div class="toogle">
		<h3 class="m_3">Değerlendirmeler</h3>
		<hr>
		<partial name="_CommentBox"></partial>
		<hr>
		@foreach (var c in Model.ListOfComments)
		{
			<hr>
			<div class="row">
				<div class="col-md-3">
					<hr>
					@c.UserName
					<hr>
					<i>@c.PublishedDate</i>
					<br>
					@for (var i = 1; i < c.Rating; i++)
					{
						<span class="starGlowN"></span>
					}
					@for (var i = (c.Rating+1); i <=5; i++)
					{
						<span class="starFadeN"></span>
					}
				</div>
				<div class="col-md-9">
					@Html.Raw(c.Comments.Replace("\n","<br>"))
				</div>
			</div>
		}
		<hr>

		<script>
			function SCRate() {
				for (var i =1; i<=@totalRating;i++)
				{
					$("#sRate"+i).attr('class','starGlowN');
				}
			}
			$(function(){
				SCRate();
			});
		</script>	
	</div>
</div>
	<!---->
	<div class="sub-cate">
		<div class=" top-nav rsidebar span_1_of_left">
			<h3 class="cate">KATEGORİLER</h3>
			<ul class="menu">
				<li>
					<ul class="kid-menu">
						@await Component.InvokeAsync("Categories")
					</ul>
				</li>
			</ul>
		</div>
		<!--initiate accordion-->
		<script type="text/javascript">
			$(function() {
			    var menu_ul = $('.menu > li > ul'),
			           menu_a  = $('.menu > li > a');
			    menu_ul.hide();
			    menu_a.click(function(e) {
			        e.preventDefault();
			        if(!$(this).hasClass('active')) {
			            menu_a.removeClass('active');
			            menu_ul.filter(':visible').slideUp('normal');
			            $(this).addClass('active').next().stop(true,true).slideDown('normal');
			        } else {
			            $(this).removeClass('active');
			            $(this).next().stop(true,true).slideUp('normal');
			        }
			    });
			
			});
		</script>
		<a class="view-all all-product" href="/products">Bütün Ürünleri Gör<span> </span></a> 	
	</div>
	<div class="clearfix"> </div>		

	<!---->
</body>
</html>

ecommerce.webui/Views/Shop/List.cshtml
@model ProductListViewModel
@{
	var products = Model.Products;
}

<!DOCTYPE html>
<html>
<head>
<title>Ürünler</title>
<link rel="stylesheet" href="/modules/bootstrap/dist/css/bootstrap.min.css" crossorigin="anonymous">
<link href="~/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
<!--theme-style-->
<link href="~/css/mystyles.css" rel="stylesheet" type="text/css" media="all" />	
<!--//theme-style-->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--fonts-->
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
<!--//fonts-->
<script src="~/js/jquery.min.js"></script>
<!--script-->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

</head>
<body>
	@await Html.PartialAsync("_header") 
	<!-- start content -->
<div class="container">
	<div class=" w_content">
		<div class="women">
				<ul class="w_nav">
					<div class="dropdown" style="margin-right: 100px;">
						<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							Sıralama
						</button>
						<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
							<a class="dropdown-item" asp-action="List" asp-route-sortOrder="@ViewData["PriceOrderInc"]">Artan Fiyat</a>
							<a class="dropdown-item" asp-action="List" asp-route-sortOrder="@ViewData["PriceOrderDesc"]">Azalan Fiyat</a>
						</div>
					</div>
				</ul>
		</div>
	</div>	
</div>
<div class="container">
	<div class="women-product">
		<!-- grids_of_4 -->
		<div class="grid-product">
			@if (products.Count == 0)
			{
				@await Html.PartialAsync("_noproduct")
			}
			else
			{
				@foreach (var product in products)
				{	
					@await Html.PartialAsync("_product",product)
				}
			}
		</div>
		<div class="row">
			<div class="col">
				<nav aria-label="Page navigation example">
					<ul class="pagination">
						@for (int i = 0; i < Model.PageInfo.TotalPages(); i++)
						{
							@if(String.IsNullOrEmpty(Model.PageInfo.CurrentCategory))
							{
								<li class="page-item @(Model.PageInfo.CurrentPage==i+1?"active":"")">
									<a class="page-link" href="/products?page=@(i+1)">
										@(i+1)
									</a>
								</li>  
							}
							else
							{
								<li class="page-item @(Model.PageInfo.CurrentPage==i+1?"active":"")">
									<a class="page-link" href="/products/@Model.PageInfo.CurrentCategory?page=@(i+1)">
										@(i+1)
									</a>
								</li> 
							}
													
						}
					</ul>
				</nav>
			</div>
		</div>	
	</div>
	<div class="sub-cate">
		<div class=" top-nav rsidebar span_1_of_left">
			<h3 class="cate">KATEGORİLER</h3>
			<ul class="menu">
				<li>
					<ul class="kid-menu">
						@await Component.InvokeAsync("Categories")
					</ul>
				</li>
			</ul>
		</div>
		<!--initiate accordion-->
		<script type="text/javascript">
			$(function() {
			    var menu_ul = $('.menu > li > ul'),
			           menu_a  = $('.menu > li > a');
			    menu_ul.hide();
			    menu_a.click(function(e) {
			        e.preventDefault();
			        if(!$(this).hasClass('active')) {
			            menu_a.removeClass('active');
			            menu_ul.filter(':visible').slideUp('normal');
			            $(this).addClass('active').next().stop(true,true).slideDown('normal');
			        } else {
			            $(this).removeClass('active');
			            $(this).next().stop(true,true).slideUp('normal');
			        }
			    });
			
			});
		</script>
		<div class=" chain-grid menu-chain">
			<a class="view-all all-product" href="/products">Bütün Ürünleri Gör<span> </span></a> 	
		</div>
		<div class="clearfix"> </div>
	</div>
	<!---->
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>